language: java
dist: trusty

script: ./gradlew build --full-stacktrace

env:
  global:
    - GRADLE_OPTS="-Xms128m -Xmx1g"

jdk:
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

notifications:
  slack: reportportal:fl6xWHVQp1jvsMmCJxYW9YKP

after_success:
  - bash <(curl -s https://codecov.io/bash)
