ignore:
- "com/epam/ta/reportportal/jooq/**"
- "com/epam/ta/reportportal/config/**"
- "com/epam/ta/reportportal/commons/accessible"
- "com/epam/ta/reportportal/commons/querygen/constant"
- "com/epam/ta/reportportal/exception"